// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMbRLoktEQbuTh8O4OGeJj_w3foHkW4w',
    appId: '1:130146230599:web:9dd3897dfa3c6a9ebf6c62',
    messagingSenderId: '130146230599',
    projectId: 'bagtothefuture-7ea0d',
    authDomain: 'bagtothefuture-7ea0d.firebaseapp.com',
    storageBucket: 'bagtothefuture-7ea0d.appspot.com',
    measurementId: 'G-M2G1FM19L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_i0pDIykQLhSshctydIE8fR7NQ1jMXg',
    appId: '1:130146230599:android:1ee9f33296df4de9bf6c62',
    messagingSenderId: '130146230599',
    projectId: 'bagtothefuture-7ea0d',
    storageBucket: 'bagtothefuture-7ea0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK2gJd92fpkL4GLQdFNrvzKs7x0PngxNE',
    appId: '1:130146230599:ios:c3f4a92ac409bea3bf6c62',
    messagingSenderId: '130146230599',
    projectId: 'bagtothefuture-7ea0d',
    storageBucket: 'bagtothefuture-7ea0d.appspot.com',
    iosBundleId: 'com.example.backToTheFuture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK2gJd92fpkL4GLQdFNrvzKs7x0PngxNE',
    appId: '1:130146230599:ios:66c078b0936782d4bf6c62',
    messagingSenderId: '130146230599',
    projectId: 'bagtothefuture-7ea0d',
    storageBucket: 'bagtothefuture-7ea0d.appspot.com',
    iosBundleId: 'com.example.backToTheFurture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeMbRLoktEQbuTh8O4OGeJj_w3foHkW4w',
    appId: '1:130146230599:web:7f070c6f3b70d2e4bf6c62',
    messagingSenderId: '130146230599',
    projectId: 'bagtothefuture-7ea0d',
    authDomain: 'bagtothefuture-7ea0d.firebaseapp.com',
    storageBucket: 'bagtothefuture-7ea0d.appspot.com',
    measurementId: 'G-2HV5LX2NT2',
  );
}
